-- Ingredient Reference Seed Data
-- Run after schema.sql is applied:
--   npm run db:migrate:local  (local)
--   npm run db:migrate:remote (production)

INSERT OR IGNORE INTO ingredient_reference (id, name, category, subcategory, abv, flavor_notes, description, brand, region) VALUES

-- ── SPIRITS: Bourbon ──────────────────────────────────────────────────────────
('ir-001', 'Bourbon',               'spirit', 'bourbon',  40.0, '["vanilla","caramel","oak","spice"]',          'American whiskey made from at least 51% corn mash', NULL, 'Kentucky'),
('ir-002', 'Buffalo Trace Bourbon', 'spirit', 'bourbon',  45.0, '["vanilla","caramel","oak","mint"]',           'Approachable, well-balanced Kentucky straight bourbon', 'Buffalo Trace', 'Kentucky'),
('ir-003', 'Maker''s Mark Bourbon', 'spirit', 'bourbon',  45.0, '["caramel","vanilla","wheat","soft"]',         'Soft wheated bourbon, red wax sealed', 'Maker''s Mark', 'Kentucky'),
('ir-004', 'Bulleit Bourbon',       'spirit', 'bourbon',  45.0, '["spice","maple","oaky","bold"]',              'High-rye mashbill, bold and spicy', 'Bulleit', 'Kentucky'),
('ir-005', 'Woodford Reserve',      'spirit', 'bourbon',  43.2, '["vanilla","dried fruit","spice","smooth"]',   'Triple distilled, full-flavored small-batch bourbon', 'Woodford Reserve', 'Kentucky'),
('ir-006', 'Wild Turkey 101',       'spirit', 'bourbon',  50.5, '["bold","vanilla","spice","long_finish"]',     'Higher proof, bold and assertive', 'Wild Turkey', 'Kentucky'),
('ir-007', 'Knob Creek Bourbon',    'spirit', 'bourbon',  50.0, '["rich","oak","honey","vanilla"]',             'Full-flavored, higher-proof small-batch bourbon', 'Knob Creek', 'Kentucky'),
('ir-008', 'Four Roses Single Barrel', 'spirit', 'bourbon', 50.0, '["floral","fruity","vanilla","spice"]',     'Floral and fruity single-barrel bourbon', 'Four Roses', 'Kentucky'),

-- ── SPIRITS: Rye Whiskey ──────────────────────────────────────────────────────
('ir-010', 'Rye Whiskey',           'spirit', 'rye',      45.0, '["spice","pepper","herbal","dry"]',            'American whiskey made from at least 51% rye grain', NULL, 'USA'),
('ir-011', 'Rittenhouse Rye',       'spirit', 'rye',      50.0, '["spice","pepper","bold","dry"]',              'Bottled-in-bond, classic cocktail rye', 'Heaven Hill', 'Kentucky'),
('ir-012', 'Sazerac Rye',           'spirit', 'rye',      45.0, '["pepper","anise","subtle","dry"]',            'Straight rye used in the eponymous cocktail', 'Buffalo Trace', 'Kentucky'),
('ir-013', 'WhistlePig 10 Year',    'spirit', 'rye',      50.0, '["spice","fruity","caramel","long"]',          'Premium 10-year aged Canadian rye', 'WhistlePig', 'Vermont'),
('ir-014', 'Bulleit Rye',           'spirit', 'rye',      45.0, '["spice","herbal","bold","fruity"]',           'High-rye mashbill (95%), clean and spicy', 'Bulleit', NULL),

-- ── SPIRITS: Scotch Whisky ────────────────────────────────────────────────────
('ir-020', 'Scotch Whisky',         'spirit', 'scotch',   40.0, '["smoky","malt","caramel","complex"]',         'Scottish whisky, often peated', NULL, 'Scotland'),
('ir-021', 'Blended Scotch',        'spirit', 'scotch',   40.0, '["malt","caramel","gentle","balanced"]',       'Blend of malt and grain whiskies', NULL, 'Scotland'),
('ir-022', 'Islay Scotch',          'spirit', 'scotch',   46.0, '["smoky","peaty","medicinal","coastal"]',      'Heavily peated scotch from Islay', NULL, 'Scotland / Islay'),
('ir-023', 'Laphroaig 10',          'spirit', 'scotch',   43.0, '["peaty","smoky","iodine","coastal"]',         'Iconic heavily peated Islay single malt', 'Laphroaig', 'Scotland / Islay'),
('ir-024', 'Glenfiddich 12',        'spirit', 'scotch',   40.0, '["fruity","pear","oak","light"]',              'Gateway single malt, widely available', 'Glenfiddich', 'Scotland / Speyside'),
('ir-025', 'Highland Scotch',       'spirit', 'scotch',   40.0, '["heather","honey","fruit","malt"]',           'Approachable non-peated highland style', NULL, 'Scotland / Highlands'),

-- ── SPIRITS: Irish Whiskey ────────────────────────────────────────────────────
('ir-030', 'Irish Whiskey',         'spirit', 'irish',    40.0, '["smooth","light","floral","malt"]',           'Triple-distilled, smooth and approachable', NULL, 'Ireland'),
('ir-031', 'Jameson',               'spirit', 'irish',    40.0, '["smooth","nutty","light","grain"]',           'The world''s most popular Irish whiskey', 'Jameson', 'Ireland'),

-- ── SPIRITS: Japanese Whisky ──────────────────────────────────────────────────
('ir-035', 'Japanese Whisky',       'spirit', 'japanese', 43.0, '["delicate","floral","subtle","balanced"]',    'Precise and refined, often peated or blended', NULL, 'Japan'),
('ir-036', 'Suntory Toki',          'spirit', 'japanese', 43.0, '["floral","honeydew","light","refreshing"]',   'Approachable blended Japanese whisky', 'Suntory', 'Japan'),

-- ── SPIRITS: Gin ─────────────────────────────────────────────────────────────
('ir-040', 'Gin',                   'spirit', 'gin',      40.0, '["juniper","botanical","citrus","herbal"]',    'Juniper-forward spirit with botanical blend', NULL, NULL),
('ir-041', 'London Dry Gin',        'spirit', 'gin',      40.0, '["juniper","citrus","dry","classic"]',         'Classic dry style, juniper dominant', NULL, 'England'),
('ir-042', 'Old Tom Gin',           'spirit', 'gin',      40.0, '["juniper","slightly_sweet","herbal"]',        'Slightly sweetened historical style of gin', NULL, NULL),
('ir-043', 'Tanqueray',             'spirit', 'gin',      47.3, '["juniper","coriander","crisp","classic"]',    'Clean, juniper-forward London Dry', 'Tanqueray', 'Scotland'),
('ir-044', 'Hendrick''s Gin',       'spirit', 'gin',      41.4, '["cucumber","rose","floral","unusual"]',       'Unusual gin with cucumber and rose', 'Hendrick''s', 'Scotland'),
('ir-045', 'Bombay Sapphire',       'spirit', 'gin',      40.0, '["crisp","floral","juniper","light"]',         'Light and aromatic vapor-infused gin', 'Bombay Sapphire', 'England'),
('ir-046', 'The Botanist',          'spirit', 'gin',      46.0, '["complex","floral","herbal","islay"]',        'Foraged botanical Islay gin', 'The Botanist', 'Scotland / Islay'),
('ir-047', 'Aviation American Gin', 'spirit', 'gin',      42.0, '["floral","lavender","cardamom","dry"]',      'New Western style, lavender and cardamom forward', 'Aviation', 'USA'),
('ir-048', 'Sloe Gin',              'spirit', 'gin',     25.0, '["berry","sweet","sloe","fruity"]',             'Gin-based liqueur made with sloe berries', NULL, 'England'),

-- ── SPIRITS: Vodka ────────────────────────────────────────────────────────────
('ir-050', 'Vodka',                 'spirit', 'vodka',    40.0, '["neutral","clean","crisp"]',                  'Neutral grain or potato spirit', NULL, NULL),
('ir-051', 'Ketel One',             'spirit', 'vodka',    40.0, '["crisp","clean","subtle","grain"]',           'Smooth Dutch wheat vodka', 'Ketel One', 'Netherlands'),
('ir-052', 'Grey Goose',            'spirit', 'vodka',    40.0, '["smooth","soft","wheat","premium"]',          'French wheat vodka, premium standard', 'Grey Goose', 'France'),
('ir-053', 'Absolut',               'spirit', 'vodka',    40.0, '["clean","wheat","neutral","versatile"]',      'Widely available Swedish wheat vodka', 'Absolut', 'Sweden'),
('ir-054', 'Tito''s Handmade Vodka','spirit', 'vodka',   40.0, '["corn","smooth","clean","light"]',            'American corn vodka, naturally gluten-free', 'Tito''s', 'USA / Texas'),

-- ── SPIRITS: Rum ─────────────────────────────────────────────────────────────
('ir-060', 'White Rum',             'spirit', 'rum',      40.0, '["light","clean","sugarcane","tropical"]',     'Unaged or lightly aged clear rum', NULL, 'Caribbean'),
('ir-061', 'Dark Rum',              'spirit', 'rum',      40.0, '["molasses","caramel","spice","rich"]',        'Aged rum with deep color and flavor', NULL, 'Caribbean'),
('ir-062', 'Aged Rum',              'spirit', 'rum',      40.0, '["vanilla","caramel","oak","tropical"]',       'Barrel-aged rum with complex flavors', NULL, 'Caribbean'),
('ir-063', 'Overproof Rum',         'spirit', 'rum',      57.0, '["bold","raw","grass","tropical"]',            'High-alcohol rum (57%+), used sparingly', NULL, 'Caribbean'),
('ir-064', 'Coconut Rum',           'spirit', 'rum',      21.0, '["coconut","tropical","sweet"]',               'Rum flavored with coconut', NULL, NULL),
('ir-065', 'Spiced Rum',            'spirit', 'rum',      35.0, '["cinnamon","vanilla","spice","sweet"]',       'Rum with added spices and flavoring', NULL, NULL),
('ir-066', 'Bacardi Superior',      'spirit', 'rum',      40.0, '["light","clean","sugarcane","neutral"]',      'Classic light Cuban-style white rum', 'Bacardi', 'Puerto Rico'),
('ir-067', 'Rhum Agricole',         'spirit', 'rum',      40.0, '["grassy","vegetal","funky","cane"]',          'French-style rum made from fresh cane juice', NULL, 'Martinique'),
('ir-068', 'Cachaça',              'spirit', 'rum',      39.0, '["grassy","funky","sugarcane","tropical"]',    'Brazilian sugarcane spirit (Caipirinha base)', NULL, 'Brazil'),

-- ── SPIRITS: Tequila ─────────────────────────────────────────────────────────
('ir-070', 'Tequila',               'spirit', 'tequila',  40.0, '["agave","citrus","earthy","clean"]',          'Agave-based Mexican spirit', NULL, 'Mexico'),
('ir-071', 'Blanco Tequila',        'spirit', 'tequila',  40.0, '["agave","citrus","fresh","bright"]',          'Unaged tequila, fresh agave flavor', NULL, 'Mexico'),
('ir-072', 'Reposado Tequila',      'spirit', 'tequila',  40.0, '["agave","oak","vanilla","balanced"]',         '2–12 months barrel aged tequila', NULL, 'Mexico'),
('ir-073', 'Añejo Tequila',         'spirit', 'tequila',  40.0, '["oak","vanilla","caramel","complex"]',        '1–3 years barrel aged tequila', NULL, 'Mexico'),
('ir-074', 'Espolòn Blanco',        'spirit', 'tequila',  40.0, '["agave","citrus","clean"]',                   'Affordable, clean blanco for cocktails', 'Espolòn', 'Mexico'),
('ir-075', 'Patrón Silver',         'spirit', 'tequila',  40.0, '["agave","herbal","smooth","clean"]',          'Smooth ultra-premium blanco', 'Patrón', 'Mexico'),

-- ── SPIRITS: Mezcal ──────────────────────────────────────────────────────────
('ir-080', 'Mezcal',                'spirit', 'mezcal',   40.0, '["smoky","agave","earthy","complex"]',         'Smoky agave spirit from Oaxaca', NULL, 'Mexico / Oaxaca'),
('ir-081', 'Del Maguey Vida',       'spirit', 'mezcal',   42.0, '["smoky","mineral","fruity","complex"]',       'Benchmark artisanal Oaxacan mezcal', 'Del Maguey', 'Mexico / Oaxaca'),
('ir-082', 'Ilegal Joven Mezcal',   'spirit', 'mezcal',   40.0, '["light_smoke","agave","accessible"]',         'Approachable joven (unaged) mezcal', 'Ilegal', 'Mexico / Oaxaca'),

-- ── SPIRITS: Brandy / Cognac ─────────────────────────────────────────────────
('ir-090', 'Brandy',                'spirit', 'brandy',   40.0, '["grape","oak","dried_fruit","smooth"]',       'Distilled wine, aged in oak', NULL, NULL),
('ir-091', 'Cognac VS',             'spirit', 'cognac',   40.0, '["grape","oak","fruity","vanilla"]',           'Young cognac, minimum 2 years aged', NULL, 'France / Cognac'),
('ir-092', 'Cognac VSOP',           'spirit', 'cognac',   40.0, '["dried_fruit","oak","spice","complex"]',      'Cognac aged minimum 4 years', NULL, 'France / Cognac'),
('ir-093', 'Armagnac',              'spirit', 'brandy',   40.0, '["rustic","prune","earthy","robust"]',         'French brandy from Gascony, more rustic than cognac', NULL, 'France / Armagnac'),
('ir-094', 'Calvados',              'spirit', 'brandy',   40.0, '["apple","oak","spice","earthy"]',             'French apple brandy from Normandy', NULL, 'France / Normandy'),
('ir-095', 'Pisco',                 'spirit', 'brandy',   43.0, '["grape","floral","fruity","clean"]',          'South American grape brandy (Pisco Sour base)', NULL, 'Peru / Chile'),

-- ── SPIRITS: Other ───────────────────────────────────────────────────────────
('ir-100', 'Absinthe',              'spirit', 'anise',    68.0, '["anise","herbal","fennel","licorice"]',       'High-proof anise and wormwood spirit', NULL, 'France / Switzerland'),
('ir-101', 'Aquavit',               'spirit', 'aquavit',  40.0, '["caraway","dill","herbal","Scandinavian"]',   'Scandinavian spirit flavored with caraway and/or dill', NULL, 'Scandinavia'),
('ir-102', 'Grappa',                'spirit', 'grappa',   40.0, '["grape","rough","floral","Italian"]',         'Italian pomace brandy', NULL, 'Italy'),
('ir-103', 'Genever',               'spirit', 'gin',      35.0, '["malt","juniper","herbal","old_world"]',      'Dutch predecessor to gin, maltier and softer', NULL, 'Netherlands'),
('ir-104', 'Soju',                  'spirit', 'other',    25.0, '["neutral","clean","mild","grain"]',           'Korean distilled spirit', NULL, 'Korea'),

-- ── LIQUEURS ─────────────────────────────────────────────────────────────────
('ir-110', 'Campari',               'liqueur', 'amaro',   24.7, '["bitter","orange","herbal","ruby"]',          'Italian bitter aperitivo, Negroni staple', 'Campari', 'Italy'),
('ir-111', 'Aperol',                'liqueur', 'amaro',   11.0, '["bitter_orange","herbal","light","sweet"]',   'Lighter, lower-ABV aperitivo (Aperol Spritz)', 'Aperol', 'Italy'),
('ir-112', 'Cynar',                 'liqueur', 'amaro',   16.5, '["artichoke","bitter","herbal","earthy"]',     'Italian bitter made from artichoke', 'Cynar', 'Italy'),
('ir-113', 'Fernet-Branca',         'liqueur', 'amaro',   39.0, '["bitter","menthol","herbal","intense"]',      'Intensely bitter Italian digestif', 'Fernet-Branca', 'Italy'),
('ir-114', 'Amaro Nonino',          'liqueur', 'amaro',   35.0, '["bittersweet","orange","herbal","elegant"]',  'Elegant Italian amaro (Paper Plane)', 'Nonino', 'Italy'),
('ir-115', 'Amaro Montenegro',      'liqueur', 'amaro',   23.0, '["orange","bittersweet","herbal","vanilla"]',  'Sweet and approachable Italian amaro', 'Montenegro', 'Italy'),
('ir-116', 'Amaro Averna',          'liqueur', 'amaro',   29.0, '["bittersweet","caramel","licorice","herbs"]', 'Sicilian amaro, sweet with herbal backbone', 'Averna', 'Italy'),
('ir-117', 'Amaro Ramazzotti',      'liqueur', 'amaro',   30.0, '["orange","herbal","bittersweet","cinnamon"]', 'Milanese amaro with citrus and spice', 'Ramazzotti', 'Italy'),
('ir-118', 'Chartreuse Green',      'liqueur', 'herbal',  55.0, '["herbal","complex","spicy","green"]',         '130 herb liqueur, intensely herbal and potent', 'Chartreuse', 'France'),
('ir-119', 'Chartreuse Yellow',     'liqueur', 'herbal',  40.0, '["sweet","herbal","mellow","milder"]',         'Sweeter, less intense sibling to Green Chartreuse', 'Chartreuse', 'France'),
('ir-120', 'Bénédictine',           'liqueur', 'herbal',  40.0, '["herbal","honey","spice","cognac"]',          'Herbal French liqueur, Vieux Carré ingredient', 'Bénédictine', 'France'),
('ir-121', 'Galliano',              'liqueur', 'herbal',  42.3, '["vanilla","anise","herbal","sweet"]',         'Sweet Italian herbal liqueur', 'Galliano', 'Italy'),
('ir-122', 'Drambuie',              'liqueur', 'herbal',  40.0, '["honey","heather","scotch","spice"]',         'Scotch-based honey liqueur (Rusty Nail)', 'Drambuie', 'Scotland'),
('ir-123', 'Cointreau',             'liqueur', 'orange',  40.0, '["orange","dry","clean","bright"]',            'Premium dry orange liqueur (Margarita, Cosmo)', 'Cointreau', 'France'),
('ir-124', 'Triple Sec',            'liqueur', 'orange',  25.0, '["orange","sweet","citrus"]',                  'Generic orange liqueur (broader category)', NULL, NULL),
('ir-125', 'Grand Marnier',         'liqueur', 'orange',  40.0, '["cognac","orange","rich","sweet"]',           'Cognac-based orange liqueur', 'Grand Marnier', 'France'),
('ir-126', 'Blue Curaçao',         'liqueur', 'orange',  20.0, '["orange","sweet","blue","tropical"]',         'Bright blue orange liqueur, decorative', NULL, NULL),
('ir-127', 'St-Germain',            'liqueur', 'floral',  20.0, '["elderflower","floral","sweet","light"]',     'French elderflower liqueur, bartender''s ketchup', 'St-Germain', 'France'),
('ir-128', 'Limoncello',            'liqueur', 'citrus',  30.0, '["lemon","sweet","citrus","Italian"]',         'Italian lemon liqueur', NULL, 'Italy'),
('ir-129', 'Maraschino Liqueur',    'liqueur', 'cherry',  32.0, '["cherry","almond","dry","nutty"]',            'Clear cherry liqueur (Aviation, Last Word)', 'Luxardo', 'Italy'),
('ir-130', 'Crème de Violette',     'liqueur', 'floral',  16.0, '["violet","floral","sweet","lavender"]',       'Violet liqueur (Aviation cocktail)', NULL, NULL),
('ir-131', 'Crème de Cassis',       'liqueur', 'berry',   20.0, '["blackcurrant","sweet","rich","berry"]',      'French blackcurrant liqueur (Kir Royale)', NULL, 'France'),
('ir-132', 'Crème de Menthe',       'liqueur', 'herbal',  25.0, '["mint","sweet","green","refreshing"]',        'Mint liqueur, green or white', NULL, NULL),
('ir-133', 'Crème de Cacao',        'liqueur', 'chocolate',20.0,'["chocolate","cocoa","sweet","vanilla"]',      'Chocolate liqueur, dark or white', NULL, NULL),
('ir-134', 'Kahlúa',               'liqueur', 'coffee',  20.0, '["coffee","chocolate","sweet","rum"]',         'Mexican coffee liqueur (Espresso Martini, White Russian)', 'Kahlúa', 'Mexico'),
('ir-135', 'Baileys Irish Cream',   'liqueur', 'cream',   17.0, '["cream","chocolate","irish_whiskey","sweet"]','Cream and Irish whiskey liqueur', 'Baileys', 'Ireland'),
('ir-136', 'Frangelico',            'liqueur', 'nut',     20.0, '["hazelnut","sweet","nutty","vanilla"]',       'Italian hazelnut liqueur', 'Frangelico', 'Italy'),
('ir-137', 'Amaretto',              'liqueur', 'nut',     28.0, '["almond","sweet","marzipan","stone_fruit"]',  'Italian almond-flavored liqueur', NULL, 'Italy'),
('ir-138', 'Midori',                'liqueur', 'fruit',   20.0, '["melon","sweet","green","tropical"]',         'Japanese green melon liqueur', 'Midori', 'Japan'),
('ir-139', 'Pimm''s No. 1',         'liqueur', 'herbal',  25.0, '["herbal","fruit","spice","refreshing"]',      'British gin-based fruit cup (Pimm''s Cup)', 'Pimm''s', 'England'),
('ir-140', 'Velvet Falernum',       'liqueur', 'spiced',  11.0, '["almond","clove","lime","spice","sweet"]',    'Barbadian syrup-liqueur, Tiki essential', 'Velvet Falernum', 'Barbados'),
('ir-141', 'Domaine de Canton',     'liqueur', 'ginger',  28.0, '["ginger","honey","VSOP","sweet"]',            'French ginger liqueur with cognac', 'Domaine de Canton', 'France'),
('ir-142', 'Lillet Blanc',          'liqueur', 'wine',    17.0, '["floral","citrus","honey","wine"]',           'French aperitif wine (Vesper, Corpse Reviver)', 'Lillet', 'France'),
('ir-143', 'Lillet Rosé',           'liqueur', 'wine',    17.0, '["floral","berry","citrus","refreshing"]',     'Rosé version of Lillet', 'Lillet', 'France'),
('ir-144', 'Aperitivo (generic)',   'liqueur', 'amaro',   11.0, '["bitter","orange","herbal","light"]',         'Generic Italian aperitivo style (like Aperol or Campari)', NULL, 'Italy'),

-- ── VERMOUTH & FORTIFIED WINE ─────────────────────────────────────────────────
('ir-150', 'Sweet Vermouth',        'wine', 'vermouth',   16.0, '["sweet","herbal","spice","fortified"]',       'Red Italian vermouth (Negroni, Manhattan)', NULL, NULL),
('ir-151', 'Dry Vermouth',          'wine', 'vermouth',   18.0, '["dry","crisp","herbal","floral"]',            'French dry vermouth (Martini, Gibson)', NULL, NULL),
('ir-152', 'Blanc Vermouth',        'wine', 'vermouth',   16.0, '["sweet","floral","white","gentle"]',          'White semi-sweet vermouth, refreshing', NULL, NULL),
('ir-153', 'Fino Sherry',           'wine', 'sherry',     15.0, '["dry","nutty","saline","delicate"]',          'Very dry sherry, great in Bamboo cocktail', NULL, 'Spain'),
('ir-154', 'Oloroso Sherry',        'wine', 'sherry',     18.0, '["nutty","rich","dried_fruit","dark"]',        'Rich, dark oxidized sherry', NULL, 'Spain'),
('ir-155', 'Port',                  'wine', 'port',       20.0, '["sweet","dried_fruit","rich","fortified"]',   'Fortified Portuguese wine', NULL, 'Portugal'),
('ir-156', 'Prosecco',              'wine', 'sparkling',  11.0, '["light","fizzy","apple","pear"]',             'Italian sparkling wine (Aperol Spritz)', NULL, 'Italy'),
('ir-157', 'Champagne',             'wine', 'sparkling',  12.0, '["yeasty","crisp","citrus","brioche"]',        'French sparkling wine (French 75)', NULL, 'France'),
('ir-158', 'Sparkling Wine',        'wine', 'sparkling',  11.0, '["fizzy","crisp","refreshing"]',               'Generic sparkling wine', NULL, NULL),

-- ── BITTERS ───────────────────────────────────────────────────────────────────
('ir-160', 'Angostura Bitters',     'bitter', 'aromatic', NULL, '["aromatic","spice","clove","cinnamon"]',      'The most classic cocktail bitters', 'Angostura', 'Trinidad'),
('ir-161', 'Peychaud''s Bitters',   'bitter', 'aromatic', NULL, '["anise","cherry","floral","gentle"]',         'Gentian-based bitters used in the Sazerac', 'Peychaud''s', 'USA / New Orleans'),
('ir-162', 'Orange Bitters',        'bitter', 'citrus',   NULL, '["orange","citrus","spice","bright"]',         'Orange zest bitters, Martini and Old Fashioned use', NULL, NULL),
('ir-163', 'Regan''s Orange Bitters','bitter','citrus',   NULL, '["orange","spicy","assertive","dry"]',         'Spicier, more assertive orange bitters', 'Regan''s', 'USA'),
('ir-164', 'Fee Brothers Orange',   'bitter', 'citrus',   NULL, '["orange","bright","clean","versatile"]',      'Classic orange bitters from Rochester, NY', 'Fee Brothers', 'USA'),
('ir-165', 'Mole Bitters',          'bitter', 'spice',    NULL, '["chocolate","chili","mole","earthy"]',        'Chocolate and chili bitters', 'Bittermens', 'USA'),
('ir-166', 'Celery Bitters',        'bitter', 'vegetable',NULL, '["celery","herbal","savory","green"]',         'Savory bitters for the Bloody Mary and others', NULL, NULL),
('ir-167', 'Grapefruit Bitters',    'bitter', 'citrus',   NULL, '["grapefruit","citrus","floral","light"]',     'Bright pink grapefruit bitters', NULL, NULL),
('ir-168', 'Cardamom Bitters',      'bitter', 'spice',    NULL, '["cardamom","spice","floral","aromatic"]',     'Exotic spice bitters for whiskey cocktails', NULL, NULL),
('ir-169', 'Chocolate Bitters',     'bitter', 'chocolate',NULL, '["chocolate","bitter","dark","cocoa"]',        'Deep dark chocolate bitters', NULL, NULL),
('ir-170', 'Lavender Bitters',      'bitter', 'floral',   NULL, '["lavender","floral","herbal","gentle"]',      'Floral bitters, pairs with gin and vodka', NULL, NULL),
('ir-171', 'Walnut Bitters',        'bitter', 'nut',      NULL, '["walnut","earthy","nutty","rich"]',           'Nutty and earthy bitters for whiskey', NULL, NULL),
('ir-172', 'Aromatic Bitters',      'bitter', 'aromatic', NULL, '["spice","herbal","complex","bittering"]',     'Generic aromatic bitters (Angostura-style)', NULL, NULL),

-- ── MIXERS & SODAS ────────────────────────────────────────────────────────────
('ir-180', 'Club Soda',             'mixer', 'soda',      0.0, '["neutral","fizzy","clean"]',                   'Carbonated water with added minerals', NULL, NULL),
('ir-181', 'Tonic Water',           'mixer', 'soda',      0.0, '["bitter","quinine","sweet","carbonated"]',    'Carbonated water with quinine (G&T)', NULL, NULL),
('ir-182', 'Ginger Beer',           'mixer', 'soda',      0.0, '["ginger","spicy","carbonated","sweet"]',      'Spicy ginger-brewed soda (Moscow Mule)', NULL, NULL),
('ir-183', 'Ginger Ale',            'mixer', 'soda',      0.0, '["ginger","mild","sweet","carbonated"]',       'Milder carbonated ginger drink', NULL, NULL),
('ir-184', 'Sparkling Water',       'mixer', 'soda',      0.0, '["neutral","fizzy","clean"]',                   'Plain carbonated water, no minerals', NULL, NULL),
('ir-185', 'Cola',                  'mixer', 'soda',      0.0, '["caramel","sweet","carbonated","spice"]',     'Classic cola mixer', NULL, NULL),
('ir-186', 'Lemon-Lime Soda',       'mixer', 'soda',      0.0, '["citrus","sweet","carbonated"]',              'Sprite, 7UP, etc.', NULL, NULL),
('ir-187', 'Cranberry Juice',       'mixer', 'juice',     0.0, '["tart","berry","red","sweet"]',               'Tart red berry juice (Cosmopolitan)', NULL, NULL),
('ir-188', 'Pineapple Juice',       'mixer', 'juice',     0.0, '["tropical","sweet","fruity","bright"]',       'Fresh or bottled pineapple juice', NULL, NULL),
('ir-189', 'Orange Juice',          'mixer', 'juice',     0.0, '["citrus","sweet","fresh","bright"]',          'Fresh squeezed or store-bought OJ', NULL, NULL),
('ir-190', 'Grapefruit Juice',      'mixer', 'juice',     0.0, '["citrus","tart","bitter","refreshing"]',      'Fresh or bottled grapefruit juice', NULL, NULL),
('ir-191', 'Apple Juice',           'mixer', 'juice',     0.0, '["apple","sweet","mild","fruit"]',             'Apple juice or cider', NULL, NULL),
('ir-192', 'Tomato Juice',          'mixer', 'juice',     0.0, '["savory","umami","vegetable","thick"]',       'Thick tomato juice (Bloody Mary)', NULL, NULL),
('ir-193', 'Coconut Water',         'mixer', 'juice',     0.0, '["tropical","light","coconut","refreshing"]',  'Hydrating coconut water', NULL, NULL),
('ir-194', 'Mango Juice',           'mixer', 'juice',     0.0, '["tropical","sweet","mango","fruity"]',        'Mango nectar or juice', NULL, NULL),
('ir-195', 'Passion Fruit Juice',   'mixer', 'juice',     0.0, '["tropical","tart","exotic","bright"]',        'Passion fruit juice or nectar', NULL, NULL),

-- ── SYRUPS ────────────────────────────────────────────────────────────────────
('ir-200', 'Simple Syrup',          'syrup', 'sugar',     0.0, '["sweet","neutral","clean"]',                   '1:1 sugar:water syrup', NULL, NULL),
('ir-201', 'Rich Simple Syrup',     'syrup', 'sugar',     0.0, '["very_sweet","thick","neutral"]',              '2:1 sugar:water syrup, thicker and sweeter', NULL, NULL),
('ir-202', 'Demerara Syrup',        'syrup', 'sugar',     0.0, '["caramel","molasses","rich","brown"]',         'Made with demerara sugar, depth of flavor', NULL, NULL),
('ir-203', 'Honey Syrup',           'syrup', 'honey',     0.0, '["honey","floral","sweet","warm"]',             'Honey diluted with water (2:1 ratio), easy to pour', NULL, NULL),
('ir-204', 'Agave Nectar',          'syrup', 'agave',     0.0, '["sweet","mild","light","tequila_pairing"]',   'Sweetener from agave plant, great with tequila', NULL, NULL),
('ir-205', 'Agave Syrup',           'syrup', 'agave',     0.0, '["sweet","mild","agave"]',                     'Agave nectar diluted with water', NULL, NULL),
('ir-206', 'Grenadine',             'syrup', 'pomegranate',0.0,'["pomegranate","sweet","red","fruity"]',        'Pomegranate syrup (Tequila Sunrise, Jack Rose)', NULL, NULL),
('ir-207', 'Orgeat',                'syrup', 'almond',    0.0, '["almond","sweet","floral","tropical"]',        'Almond and orange blossom syrup (Mai Tai)', NULL, NULL),
('ir-208', 'Falernum',              'syrup', 'spiced',    0.0, '["almond","lime","clove","ginger","tropical"]', 'Spiced syrup from Barbados (non-alcoholic version)', NULL, NULL),
('ir-209', 'Ginger Syrup',         'syrup', 'spiced',    0.0, '["ginger","spicy","sweet","warm"]',             'Homemade or commercial ginger syrup', NULL, NULL),
('ir-210', 'Raspberry Syrup',       'syrup', 'berry',     0.0, '["raspberry","fruity","sweet","bright"]',       'Sweet raspberry syrup', NULL, NULL),
('ir-211', 'Lavender Syrup',        'syrup', 'floral',    0.0, '["lavender","floral","sweet","fragrant"]',      'Floral lavender-infused syrup', NULL, NULL),
('ir-212', 'Cinnamon Syrup',        'syrup', 'spiced',    0.0, '["cinnamon","warm","spice","sweet"]',           'Cinnamon-infused simple syrup', NULL, NULL),
('ir-213', 'Passion Fruit Syrup',   'syrup', 'tropical',  0.0, '["tropical","tart","sweet","exotic"]',         'Passion fruit-flavored syrup (Pornstar Martini)', NULL, NULL),
('ir-214', 'Coconut Cream',         'syrup', 'tropical',  0.0, '["coconut","rich","tropical","thick"]',        'Canned coconut cream (Piña Colada)', NULL, NULL),
('ir-215', 'Elderflower Cordial',   'syrup', 'floral',    0.0, '["elderflower","floral","sweet","light"]',      'Non-alcoholic elderflower syrup', NULL, NULL),
('ir-216', 'Raspberry Cordial',     'syrup', 'berry',     0.0, '["raspberry","sweet","berry","bright"]',        'Raspberry juice concentrate sweetened', NULL, NULL),
('ir-217', 'Rose Syrup',            'syrup', 'floral',    0.0, '["rose","floral","sweet","fragrant"]',          'Rose-flavored syrup (Ramos Gin Fizz variation)', NULL, NULL),
('ir-218', 'Banana Syrup',          'syrup', 'tropical',  0.0, '["banana","tropical","sweet","fruit"]',         'Banana-flavored syrup', NULL, NULL),
('ir-219', 'Hibiscus Syrup',        'syrup', 'floral',    0.0, '["hibiscus","tart","floral","ruby"]',           'Tart floral hibiscus syrup', NULL, NULL),

-- ── FRESH / CITRUS ────────────────────────────────────────────────────────────
('ir-230', 'Fresh Lemon Juice',     'fresh', 'citrus',    0.0, '["tart","citrus","bright","acid"]',             'Freshly squeezed lemon juice', NULL, NULL),
('ir-231', 'Fresh Lime Juice',      'fresh', 'citrus',    0.0, '["tart","citrus","sharp","acid"]',              'Freshly squeezed lime juice', NULL, NULL),
('ir-232', 'Fresh Orange Juice',    'fresh', 'citrus',    0.0, '["citrus","sweet","fresh","bright"]',           'Freshly squeezed orange juice', NULL, NULL),
('ir-233', 'Fresh Grapefruit Juice','fresh', 'citrus',    0.0, '["citrus","tart","bitter","refreshing"]',       'Freshly squeezed grapefruit juice', NULL, NULL),
('ir-234', 'Lemon',                 'fresh', 'citrus',    0.0, '["citrus","tart","bright"]',                    'Whole lemon (for juice, zest, or garnish)', NULL, NULL),
('ir-235', 'Lime',                  'fresh', 'citrus',    0.0, '["citrus","tart","sharp"]',                     'Whole lime (for juice, zest, or garnish)', NULL, NULL),
('ir-236', 'Orange',                'fresh', 'citrus',    0.0, '["citrus","sweet","bright"]',                   'Whole orange (for juice, zest, or garnish)', NULL, NULL),
('ir-237', 'Grapefruit',            'fresh', 'citrus',    0.0, '["citrus","bitter","tart"]',                    'Whole grapefruit', NULL, NULL),
('ir-238', 'Pineapple',             'fresh', 'tropical',  0.0, '["tropical","sweet","fruity","bright"]',        'Fresh pineapple (chunks or juice)', NULL, NULL),
('ir-239', 'Egg White',             'fresh', 'egg',       0.0, '["frothy","neutral","protein","silky"]',        'Egg white for foam (Whiskey Sour, Clover Club)', NULL, NULL),
('ir-240', 'Whole Egg',             'fresh', 'egg',       0.0, '["creamy","rich","protein","emulsifier"]',      'Whole egg for flips and nogs', NULL, NULL),
('ir-241', 'Cucumber',              'fresh', 'vegetable', 0.0, '["fresh","cooling","light","green"]',           'Fresh cucumber for muddling or garnish', NULL, NULL),
('ir-242', 'Mint',                  'fresh', 'herb',      0.0, '["minty","cooling","fresh","aromatic"]',        'Fresh mint leaves (Mojito, Mint Julep)', NULL, NULL),
('ir-243', 'Basil',                 'fresh', 'herb',      0.0, '["herbal","anise","aromatic","savory"]',        'Fresh basil leaves for muddling', NULL, NULL),
('ir-244', 'Rosemary',              'fresh', 'herb',      0.0, '["piney","herbal","aromatic","resinous"]',      'Fresh rosemary sprig for garnish or infusion', NULL, NULL),
('ir-245', 'Thyme',                 'fresh', 'herb',      0.0, '["herbal","savory","floral","delicate"]',       'Fresh thyme for garnish or syrup', NULL, NULL),
('ir-246', 'Jalapeño',              'fresh', 'spice',     0.0, '["spicy","heat","vegetal","green"]',            'Fresh jalapeño for heat and bite', NULL, NULL),
('ir-247', 'Fresh Pineapple Juice', 'fresh', 'tropical',  0.0, '["tropical","sweet","bright","acid"]',          'Freshly pressed pineapple juice', NULL, NULL),
('ir-248', 'Cold Brew Coffee',      'fresh', 'coffee',    0.0, '["coffee","bold","bitter","smooth"]',           'Strong cold brew concentrate', NULL, NULL),
('ir-249', 'Espresso',              'fresh', 'coffee',    0.0, '["coffee","intense","bitter","rich"]',          'Freshly pulled espresso shot (Espresso Martini)', NULL, NULL),
('ir-250', 'Heavy Cream',           'fresh', 'dairy',     0.0, '["rich","creamy","fat","smooth"]',              'Heavy whipping cream for floats and frappes', NULL, NULL),

-- ── SPICES / OTHER ────────────────────────────────────────────────────────────
('ir-260', 'Salt',                  'spice', 'mineral',   NULL, '["saline","mineral","enhancer"]',              'Pinch of salt to enhance cocktail flavors', NULL, NULL),
('ir-261', 'Sugar',                 'spice', 'sweetener', NULL, '["sweet","neutral","white"]',                  'Granulated white sugar', NULL, NULL),
('ir-262', 'Demerara Sugar',        'spice', 'sweetener', NULL, '["caramel","brown","molasses","raw"]',         'Raw brown sugar with caramel notes', NULL, NULL),
('ir-263', 'Nutmeg',                'spice', 'spice',     NULL, '["warm","nutty","aromatic","spice"]',          'Freshly grated nutmeg for garnish', NULL, NULL),
('ir-264', 'Cinnamon',              'spice', 'spice',     NULL, '["warm","spice","sweet","aromatic"]',          'Ground cinnamon or cinnamon stick', NULL, NULL),
('ir-265', 'Star Anise',            'spice', 'spice',     NULL, '["anise","licorice","aromatic","Chinese"]',    'Star-shaped spice, anise flavor', NULL, NULL),
('ir-266', 'Cloves',                'spice', 'spice',     NULL, '["spicy","aromatic","warm","intense"]',        'Whole or ground cloves', NULL, NULL),
('ir-267', 'Black Pepper',          'spice', 'spice',     NULL, '["peppery","spicy","earthy","sharp"]',         'Freshly cracked black pepper', NULL, NULL),
('ir-268', 'Cayenne',               'spice', 'spice',     NULL, '["spicy","heat","peppery","earthy"]',          'Cayenne pepper for heat in cocktails', NULL, NULL),
('ir-269', 'Vanilla Extract',       'spice', 'flavoring', NULL, '["vanilla","sweet","aromatic","warm"]',        'Pure vanilla extract', NULL, NULL),
('ir-270', 'Activated Charcoal',    'spice', 'flavoring', NULL, '["neutral","black","theatrical"]',             'Culinary activated charcoal for dramatic black color', NULL, NULL),
('ir-271', 'Honey',                 'spice', 'sweetener', NULL, '["sweet","floral","warm","natural"]',          'Raw honey, used directly or diluted as syrup', NULL, NULL),
('ir-272', 'Maple Syrup',           'spice', 'sweetener', NULL, '["maple","caramel","warm","sweet"]',           'Pure maple syrup for richness', NULL, NULL),
('ir-273', 'Tajín',                'spice', 'spice',     NULL, '["chili","lime","saline","spicy"]',             'Mexican chili-lime-salt seasoning for rims', NULL, 'Mexico'),
('ir-274', 'Fee Foam',              'other', 'modifier',  NULL, '["neutral","foaming","vegan"]',                'Vegan foaming agent, substitute for egg white', 'Fee Brothers', 'USA'),
('ir-275', 'Aquafaba',              'fresh', 'egg',       NULL, '["neutral","foaming","vegan","watery"]',       'Chickpea brine, vegan egg white substitute', NULL, NULL),
('ir-276', 'Cream of Coconut',      'syrup', 'tropical',  0.0, '["coconut","sweet","thick","tropical"]',       'Sweetened coconut cream (Piña Colada)', NULL, NULL),
('ir-277', 'Worcestershire Sauce',  'other', 'condiment', NULL, '["umami","savory","tangy","complex"]',         'Worcestershire sauce for Bloody Mary', NULL, NULL),
('ir-278', 'Hot Sauce',             'other', 'condiment', NULL, '["spicy","vinegar","heat","tangy"]',           'Tabasco or similar hot sauce for Bloody Mary', NULL, NULL),
('ir-279', 'Celery Salt',           'spice', 'mineral',   NULL, '["savory","celery","saline"]',                 'Celery salt for Bloody Mary rims', NULL, NULL),
('ir-280', 'Maraschino Cherry',     'other', 'garnish',   NULL, '["sweet","cherry","artificial","red"]',        'Classic cocktail cherry garnish', NULL, NULL),
('ir-281', 'Luxardo Cherry',        'other', 'garnish',   NULL, '["cherry","rich","marzipan","Italian"]',       'Premium marasca cherry in maraschino liqueur', 'Luxardo', 'Italy'),
('ir-282', 'Cocktail Olive',        'other', 'garnish',   NULL, '["saline","savory","olive","briny"]',          'Cocktail olive for Martinis', NULL, NULL),
('ir-283', 'Olive Brine',           'other', 'condiment', NULL, '["saline","briny","savory"]',                  'Olive jar brine for a Dirty Martini', NULL, NULL);

-- Add FTS index entries if needed (ingredient reference is not in the FTS table yet; queries hit it directly)
