/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Run `npm run cf-typegen` to regenerate after changing wrangler.jsonc

declare namespace Cloudflare {
  interface Env {
    dramscript_db: D1Database;
    SESSIONS: KVNamespace;
    IMAGES: R2Bucket;
    ASSETS: Fetcher;
    AI: Ai;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    SESSION_SECRET: string;
  }
}
interface Env extends Cloudflare.Env {}
